### ISSUE TITLE
error when there are more than 100 items in the s3 bucket

### ISSUE THREAD

**Issue by harishmk** [awslabs/aws-data-exchange-publisher-coordinator#11]
started getting this error after the s3 bucket grew to more than 100 files.
is there a work around to this?

> [ERROR] ValidationException: An error occurred (ValidationException) when calling the CreateJob operation: The following parameter(s) are not valid: "Details.ImportAssetsFromS3.AssetSources" must contain less than or equal to 100 items.
> Traceback (most recent call last):
>   File "/var/task/app.py", line 101, in lambda_handler
>     raise e
>   File "/var/task/app.py", line 69, in lambda_handler
>     jobresponse = dataexchange.create_job(Type='IMPORT_ASSETS_FROM_S3',Details=revisiondetails)
>   File "/var/runtime/botocore/client.py", line 391, in _api_call
>     return self._make_api_call(operation_name, kwargs)
>   File "/var/runtime/botocore/client.py", line 719, in _make_api_call
>     raise error_class(parsed_response, operation_name)
>

**Comment by harishmk** [comment]
could someone comment on this please?
